// // importing the faer library as a module
// import { faker } from 'https://esm.sh/@faker-js/faker';

// // Initialize global variables
// // random text which is going to be generated by faker
// let randomText = '';
// // start and end time
// let startTime, endTime;
// // to keep the count of the time
// let correctWords = 0;

// // Function to generate a random paragraph
// // used faker for it:

// function getRandomParagraph(numSentences) {
//     let paragraph = '';
//     for (let i = 0; i < numSentences; i++) {
//         paragraph += faker.lorem.sentence() + ' ';
//     }
//     return paragraph.trim(); // Ensure no extra space at the end
// }

// // Add event listener to the button
// document.getElementById("button").addEventListener("click", function () {
//     randomText = getRandomParagraph(1);
//     document.getElementById("main-content").innerText = randomText;
//     startTypingTest();
// });

// // Start the typing test
// function startTypingTest() {
//     const inputBox = document.getElementById("input-box");
//     inputBox.value = '';
    
//     inputBox.focus();
//     correctWords = 0;
//     document.getElementById("words-correct").textContent = `Words Correct: ${correctWords}`;
//     startTime = new Date();
// }

// // Function to check input
// function checkInput() {
//     const inputBox = document.getElementById("input-box");
//     const typedText = inputBox.value;
//     const words = randomText.split(' ');
//     const typedWords = typedText.split(' ');

//     let correctCount = 0;
//     for (let i = 0; i < typedWords.length; i++) {
//         if (typedWords[i] === words[i]) {
//             correctCount++;
//         }
//     }

//     correctWords = correctCount;
//     document.getElementById("words-correct").textContent = `Words Correct: ${correctWords}`;

//     if (typedText === randomText) {
//         endTime = new Date();
//         const timeTaken = Math.round((endTime - startTime) / 1000); // Time in seconds
//         document.getElementById("total-time").textContent = `Total Time: ${timeTaken}s`;
//         const wpm = Math.round((correctWords / timeTaken) * 60); // Calculate WPM
//         document.getElementById("wpm").textContent = `WPM: ${wpm}`;
//     }
// }

// // Add event listener to the input box to check the input
// document.getElementById("input-box").addEventListener("input", checkInput);


// Importing the Faker library as a module
// import { faker } from 'https://esm.sh/@faker-js/faker';

// // Initialize global variables
// let randomText = ''; // Random text which is going to be generated by faker
// let startTime, endTime; // Start and end time
// let correctWords = 0; // To keep the count of correct words
// let timerStarted = false; // Flag to check if the timer has started

// // Function to generate a random paragraph
// function getRandomParagraph(numSentences) {
//     let paragraph = '';
//     for (let i = 0; i < numSentences; i++) {
//         paragraph += faker.lorem.sentence() + ' ';
//     }
//     return paragraph.trim(); // Ensure no extra space at the end
// }

// // Add event listener to the button
// document.getElementById("button").addEventListener("click", function () {
//     randomText = getRandomParagraph(1);
//     document.getElementById("main-content").innerText = randomText;
//     startTypingTest();
// });

// // Start the typing test
// function startTypingTest() {
//     const inputBox = document.getElementById("input-box");
//     inputBox.value = '';
//     inputBox.focus();
//     correctWords = 0;
//     document.getElementById("words-correct").textContent = `Words Correct: ${correctWords}`;
//     timerStarted = false; // Reset the timer start flag
// }

// // Function to check input
// function checkInput() {
//     const inputBox = document.getElementById("input-box");
//     const typedText = inputBox.value;
//     const words = randomText.split(' ');
//     const typedWords = typedText.split(' ');

//     // Start the timer if it hasn't been started yet
//     if (!timerStarted) {
//         startTime = new Date();
//         timerStarted = true;
//     }

//     let correctCount = 0;
//     for (let i = 0; i < typedWords.length; i++) {
//         if (typedWords[i] === words[i]) {
//             correctCount++;
//         }
//     }

//     correctWords = correctCount;
//     document.getElementById("words-correct").textContent = `Words Correct: ${correctWords}`;

//     if (typedText === randomText) {
//         endTime = new Date();
//         const timeTaken = Math.round((endTime - startTime) / 1000); // Time in seconds
//         document.getElementById("total-time").textContent = `Total Time: ${timeTaken}s`;
//         const wpm = Math.round((correctWords / timeTaken) * 60); // Calculate WPM
//         document.getElementById("wpm").textContent = `WPM: ${wpm}`;
//     }
// }

// // Add event listener to the input box to check the input
// document.getElementById("input-box").addEventListener("input", checkInput);


// Importing the Faker library as a module
import { faker } from 'https://esm.sh/@faker-js/faker';

// Initialize global variables
let randomText = ''; // Random text which is going to be generated by faker
let startTime, endTime; // Start and end time
let correctWords = 0; // To keep the count of correct words
let timerStarted = false; // Flag to check if the timer has started
let timerInterval; // To store the interval ID

// Function to generate a random paragraph
function getRandomParagraph(numSentences) {
    let paragraph = '';
    for (let i = 0; i < numSentences; i++) {
        paragraph += faker.lorem.sentence() + ' ';
    }
    return paragraph.trim(); // Ensure no extra space at the end
}

// Add event listener to the button
document.getElementById("button").addEventListener("click", function () {
    randomText = getRandomParagraph(1);
    document.getElementById("main-content").innerText = randomText;
    startTypingTest();
});

// Add event listener to the stop button
document.getElementById("stop-button").addEventListener("click", function () {
    stopTimer();
});

// Start the typing test
function startTypingTest() {
    const inputBox = document.getElementById("input-box");
    inputBox.value = '';
    inputBox.focus();
    correctWords = 0;
    document.getElementById("words-correct").textContent = `Words Correct: ${correctWords}`;
    document.getElementById("total-time").textContent = `Total Time: 0s`;
    document.getElementById("wpm").textContent = `WPM: 0`;
    document.getElementById("accuracy").textContent = `Accuracy: 0%`;
    
    if (timerInterval) {
        clearInterval(timerInterval); // Clear any existing timer
    }
    
    timerStarted = false; // Reset the timer start flag
}

// Function to start the timer
function startTimer() {
    startTime = new Date();
    timerInterval = setInterval(updateTimer, 1000); // Update every second
}

// Function to stop the timer
function stopTimer() {
    if (timerInterval) {
        clearInterval(timerInterval); // Stop the timer
        timerInterval = null; // Clear the interval ID
    }
}

// Function to update the timer display, WPM, and accuracy
function updateTimer() {
    const currentTime = new Date();
    const timeTaken = Math.round((currentTime - startTime) / 1000); // Elapsed time in seconds
    document.getElementById("total-time").textContent = `Total Time: ${timeTaken}s`;
    
    const inputBox = document.getElementById("input-box");
    const typedText = inputBox.value;
    const words = randomText.split(' ');
    const typedWords = typedText.split(' ');

    // Calculate correct words and accuracy
    let correctCount = 0;
    for (let i = 0; i < typedWords.length; i++) {
        if (typedWords[i] === words[i]) {
            correctCount++;
        }
    }

    correctWords = correctCount;
    document.getElementById("words-correct").textContent = `Words Correct: ${correctWords}`;
    
    // Calculate WPM
    const wpm = Math.round((correctWords / timeTaken) * 60); // Calculate WPM based on correct words
    document.getElementById("wpm").textContent = `WPM: ${wpm}`;
    
    // Calculate Accuracy
    const totalWords = words.length;
    const accuracy = Math.round((correctWords / totalWords) * 100); // Calculate accuracy
    document.getElementById("accuracy").textContent = `Accuracy: ${accuracy}%`;
}

// Function to handle user input
function checkInput() {
    if (!timerStarted) {
        startTimer(); // Start the timer if it hasn't been started yet
        timerStarted = true;
    }

    updateTimer(); // Update timer, WPM, and accuracy
}

// Add event listener to the input box to check the input
document.getElementById("input-box").addEventListener("input", checkInput);
